version: "3.1"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    
  cataloguedbservice:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: urbanco
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cataloguedb
    volumes:
      - cataloguedbvolume:/varlib/postgresql/data

  catalogueservice:
    # image: bradleynz/urbanco:catalogueservice
    image: catalogueservice:latest
    environment:
      DB_USER: urbanco
      DB_PASS: admin
      DB: cataloguedb
      DB_HOST: cataloguedbservice
    links:
      - cataloguedbservice

  # apigateway:
  # # image: bradleynz/urbanco:apigateway
  #   image: apigateway:latest
  #   links:
  #     - catalogueservice

  accountdbservice:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: urbanco
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: accountdb
    volumes:
      - accountdbvolume:/varlib/postgresql/data

  accountservice:
    image: accountservice:latest
    environment:
      DB_USER: urbanco
      DB_PASS: admin
      DB: accountdb
      DB_HOST: accountdbservice
    ports:
      - 5001:5000
    links:
      - accountdbservice

  frontendservice:
    # image: bradleynz/urbanco:frontendservice
    image: frontendservice:latest
    ports:
      - 80:5000
    links:
      - catalogueservice
      - accountservice

volumes:
  cataloguedbvolume:
  accountdbvolume: