version: "3.1"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080

  cataloguedbservice:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: urbanco
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cataloguedb
    volumes:
      - cataloguedbvolume:/varlib/postgresql/data

  catalogueservice:
    image: catalogueservice:latest
    environment:
      DB_USER: urbanco
      DB_PASS: admin
      DB: cataloguedb
      DB_HOST: cataloguedbservice
    links:
      - cataloguedbservice

  frontendservice:
    image: frontendservice:latest
    ports:
      - 80:5000
    links:
      - catalogueservice

volumes:
  cataloguedbvolume: